export type ShipDef = {
  id: number;
  name: string;
  scoreRequired: number;
};

export const SHIPS: ShipDef[] = [
  { id:  1, name: 'VIPER MK-I',       scoreRequired:     0 },
  { id:  2, name: 'VIPER MK-II',      scoreRequired:    15 },
  { id:  3, name: 'VIPER MK-III',     scoreRequired:    62 },
  { id:  4, name: 'RAPTOR MK-I',      scoreRequired:   140 },
  { id:  5, name: 'RAPTOR MK-II',     scoreRequired:   250 },
  { id:  6, name: 'RAPTOR MK-III',    scoreRequired:   380 },
  { id:  7, name: 'COBRA MK-I',       scoreRequired:   550 },
  { id:  8, name: 'COBRA MK-II',      scoreRequired:   750 },
  { id:  9, name: 'COBRA MK-III',     scoreRequired:   980 },
  { id: 10, name: 'HAWK MK-I',        scoreRequired:  1200 },
  { id: 11, name: 'HAWK MK-II',       scoreRequired:  1500 },
  { id: 12, name: 'SABRE MK-I',       scoreRequired:  1900 },
  { id: 13, name: 'SABRE MK-II',      scoreRequired:  2200 },
  { id: 14, name: 'SABRE MK-III',     scoreRequired:  2600 },
  { id: 15, name: 'PHANTOM MK-I',     scoreRequired:  3000 },
  { id: 16, name: 'PHANTOM MK-II',    scoreRequired:  3500 },
  { id: 17, name: 'TITAN MK-I',       scoreRequired:  3900 },
  { id: 18, name: 'TITAN MK-II',      scoreRequired:  4400 },
  { id: 19, name: 'STEALTH MK-I',     scoreRequired:  5000 },
  { id: 20, name: 'STEALTH MK-II',    scoreRequired:  5600 },
  { id: 21, name: 'LANCER MK-I',      scoreRequired:  6200 },
  { id: 22, name: 'LANCER MK-II',     scoreRequired:  6800 },
  { id: 23, name: 'LANCER MK-III',    scoreRequired:  7400 },
  { id: 24, name: 'RAZOR MK-I',       scoreRequired:  8100 },
  { id: 25, name: 'RAZOR MK-II',      scoreRequired:  8900 },
  { id: 26, name: 'RAZOR MK-III',     scoreRequired:  9600 },
  { id: 27, name: 'GHOST MK-I',       scoreRequired: 10000 },
  { id: 28, name: 'GHOST MK-II',      scoreRequired: 11000 },
  { id: 29, name: 'GHOST MK-III',     scoreRequired: 12000 },
  { id: 30, name: 'CRUSADER MK-I',    scoreRequired: 13000 },
  { id: 31, name: 'CRUSADER MK-II',   scoreRequired: 14000 },
  { id: 32, name: 'CRUSADER MK-III',  scoreRequired: 15000 },
  { id: 33, name: 'SPECTRE MK-I',     scoreRequired: 16000 },
  { id: 34, name: 'SPECTRE MK-II',    scoreRequired: 17000 },
  { id: 35, name: 'SPECTRE MK-III',   scoreRequired: 18000 },
  { id: 36, name: 'VALKYRIE MK-I',    scoreRequired: 19000 },
  { id: 37, name: 'VALKYRIE MK-II',   scoreRequired: 20000 },
  { id: 38, name: 'VALKYRIE MK-III',  scoreRequired: 21000 },
  { id: 39, name: 'WRAITH MK-I',      scoreRequired: 22000 },
  { id: 40, name: 'WRAITH MK-II',     scoreRequired: 23000 },
  { id: 41, name: 'SHADOW MK-I',      scoreRequired: 25000 },
  { id: 42, name: 'SHADOW MK-II',     scoreRequired: 26000 },
  { id: 43, name: 'SHADOW MK-III',    scoreRequired: 27000 },
  { id: 44, name: 'PREDATOR MK-I',    scoreRequired: 28000 },
  { id: 45, name: 'PREDATOR MK-II',   scoreRequired: 30000 },
  { id: 46, name: 'PREDATOR MK-III',  scoreRequired: 31000 },
  { id: 47, name: 'HARBINGER MK-I',   scoreRequired: 33000 },
  { id: 48, name: 'HARBINGER MK-II',  scoreRequired: 34000 },
  { id: 49, name: 'NEMESIS MK-I',     scoreRequired: 35000 },
  { id: 50, name: 'NEMESIS MK-II',    scoreRequired: 37000 },
  { id: 51, name: 'NEMESIS MK-III',   scoreRequired: 38000 },
  { id: 52, name: 'REAPER MK-I',      scoreRequired: 40000 },
  { id: 53, name: 'REAPER MK-II',     scoreRequired: 42000 },
  { id: 54, name: 'REAPER MK-III',    scoreRequired: 43000 },
  { id: 55, name: 'OMEGA MK-I',       scoreRequired: 45000 },
  { id: 56, name: 'OMEGA MK-II',      scoreRequired: 47000 },
  { id: 57, name: 'OMEGA MK-III',     scoreRequired: 48000 },
  { id: 58, name: 'APEX',             scoreRequired: 50000 },
];
