import { CarConfig } from './types';

export const CARS: CarConfig[] = [
  {
    id: 'jeep',
    name: 'Jeep',
    description: 'All-terrain SUV. Balanced grip and endurance.',
    image: require('../../../assets/cars/car_jeep.png'),
    color: '#D22828',
    speed: 3,
    power: 3,
    fuel: 4,
    maxSpeed: 300,
    enginePower: 520,
    fuelRate: 3.5,
    brakePower: 700,
  },
  {
    id: 'sports',
    name: 'Sports Car',
    description: 'Blazing fast on flat ground. Struggles on steep hills.',
    image: require('../../../assets/cars/car_sports.png'),
    color: '#D4A800',
    speed: 5,
    power: 2,
    fuel: 2,
    maxSpeed: 460,
    enginePower: 400,
    fuelRate: 5.5,
    brakePower: 850,
  },
  {
    id: 'truck',
    name: 'Truck',
    description: 'Heavy hauler with serious climbing power.',
    image: require('../../../assets/cars/car_truck.png'),
    color: '#1A64C8',
    speed: 2,
    power: 5,
    fuel: 3,
    maxSpeed: 240,
    enginePower: 700,
    fuelRate: 4.0,
    brakePower: 600,
  },
  {
    id: 'monster',
    name: 'Monster Truck',
    description: 'Conquers anything. Fuel hungry beast.',
    image: require('../../../assets/cars/car_monster.png'),
    color: '#148C2A',
    speed: 2,
    power: 5,
    fuel: 1,
    maxSpeed: 220,
    enginePower: 820,
    fuelRate: 7.0,
    brakePower: 550,
  },
];
